package com.employee.Employee.model;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * KategoriKemampuan generated by hbm2java
 */
@Entity
@Table(name = "kategori_kemampuan", schema = "public")
public class KategoriKemampuan implements java.io.Serializable {

	private int idKategori;
	private String namaKategori;
	private Set<Kemampuan> kemampuans = new HashSet<Kemampuan>(0);

	public KategoriKemampuan() {
	}

	public KategoriKemampuan(int idKategori, String namaKategori) {
		this.idKategori = idKategori;
		this.namaKategori = namaKategori;
	}

	public KategoriKemampuan(int idKategori, String namaKategori, Set<Kemampuan> kemampuans) {
		this.idKategori = idKategori;
		this.namaKategori = namaKategori;
		this.kemampuans = kemampuans;
	}

	@Id
	@SequenceGenerator(name="generator_kategori_kemampuan_id_kategori_seq", sequenceName="kategori_kemampuan_id_kategori_seq", schema = "public", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_kategori_kemampuan_id_kategori_seq")
	@Column(name = "id_kategori", unique = true, nullable = false)
	public int getIdKategori() {
		return this.idKategori;
	}

	public void setIdKategori(int idKategori) {
		this.idKategori = idKategori;
	}

	@Column(name = "nama_kategori", nullable = false, length = 128)
	public String getNamaKategori() {
		return this.namaKategori;
	}

	public void setNamaKategori(String namaKategori) {
		this.namaKategori = namaKategori;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kategoriKemampuan")
	public Set<Kemampuan> getKemampuans() {
		return this.kemampuans;
	}

	public void setKemampuans(Set<Kemampuan> kemampuans) {
		this.kemampuans = kemampuans;
	}

}
