package com.employee.Employee.model;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pendapatan generated by hbm2java
 */
@Entity
@Table(name = "pendapatan", schema = "public")
public class Pendapatan implements java.io.Serializable {

	private int idPendapatan;
	private Karyawan karyawan;
	private Date tanggalGaji;
	private BigDecimal gajiPokok;
	private BigDecimal tunjanganKeluarga;
	private BigDecimal tunjanganPegawai;
	private BigDecimal tunjanganTransport;
	private BigDecimal gajiKotor;
	private BigDecimal pphPerbulan;
	private BigDecimal bpjs;
	private BigDecimal gajiBersih;
	private Integer lamaLembur;
	private BigDecimal uangLembur;
	private Integer variableBonus;
	private BigDecimal uangBonus;
	private BigDecimal takeHomePay;

	public Pendapatan() {
	}

	public Pendapatan(int idPendapatan, Date tanggalGaji, BigDecimal gajiPokok, BigDecimal tunjanganKeluarga,
			BigDecimal tunjanganPegawai, BigDecimal tunjanganTransport, BigDecimal gajiKotor, BigDecimal pphPerbulan,
			BigDecimal bpjs, BigDecimal gajiBersih, BigDecimal uangLembur, BigDecimal uangBonus,
			BigDecimal takeHomePay) {
		this.idPendapatan = idPendapatan;
		this.tanggalGaji = tanggalGaji;
		this.gajiPokok = gajiPokok;
		this.tunjanganKeluarga = tunjanganKeluarga;
		this.tunjanganPegawai = tunjanganPegawai;
		this.tunjanganTransport = tunjanganTransport;
		this.gajiKotor = gajiKotor;
		this.pphPerbulan = pphPerbulan;
		this.bpjs = bpjs;
		this.gajiBersih = gajiBersih;
		this.uangLembur = uangLembur;
		this.uangBonus = uangBonus;
		this.takeHomePay = takeHomePay;
	}

	public Pendapatan(int idPendapatan, Karyawan karyawan, Date tanggalGaji, BigDecimal gajiPokok,
			BigDecimal tunjanganKeluarga, BigDecimal tunjanganPegawai, BigDecimal tunjanganTransport,
			BigDecimal gajiKotor, BigDecimal pphPerbulan, BigDecimal bpjs, BigDecimal gajiBersih, Integer lamaLembur,
			BigDecimal uangLembur, Integer variableBonus, BigDecimal uangBonus, BigDecimal takeHomePay) {
		this.idPendapatan = idPendapatan;
		this.karyawan = karyawan;
		this.tanggalGaji = tanggalGaji;
		this.gajiPokok = gajiPokok;
		this.tunjanganKeluarga = tunjanganKeluarga;
		this.tunjanganPegawai = tunjanganPegawai;
		this.tunjanganTransport = tunjanganTransport;
		this.gajiKotor = gajiKotor;
		this.pphPerbulan = pphPerbulan;
		this.bpjs = bpjs;
		this.gajiBersih = gajiBersih;
		this.lamaLembur = lamaLembur;
		this.uangLembur = uangLembur;
		this.variableBonus = variableBonus;
		this.uangBonus = uangBonus;
		this.takeHomePay = takeHomePay;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "generator_pendapatan_id_pendapatan_seq")
	@SequenceGenerator(name="generator_pendapatan_id_pendapatan_seq", sequenceName = "pendapatan_id_pendapatan_seq", schema = "public", allocationSize = 1)
	@Column(name = "id_pendapatan", unique = true, nullable = false)
	public int getIdPendapatan() {
		return this.idPendapatan;
	}

	public void setIdPendapatan(int idPendapatan) {
		this.idPendapatan = idPendapatan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_karyawan")
	public Karyawan getKaryawan() {
		return this.karyawan;
	}

	public void setKaryawan(Karyawan karyawan) {
		this.karyawan = karyawan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tanggal_gaji", nullable = false, length = 13)
	public Date getTanggalGaji() {
		return this.tanggalGaji;
	}

	public void setTanggalGaji(Date tanggalGaji) {
		this.tanggalGaji = tanggalGaji;
	}

	@Column(name = "gaji_pokok", nullable = false, precision = 16, scale = 4)
	public BigDecimal getGajiPokok() {
		return this.gajiPokok;
	}

	public void setGajiPokok(BigDecimal gajiPokok) {
		this.gajiPokok = gajiPokok;
	}

	@Column(name = "tunjangan_keluarga", nullable = false, precision = 16, scale = 4)
	public BigDecimal getTunjanganKeluarga() {
		return this.tunjanganKeluarga;
	}

	public void setTunjanganKeluarga(BigDecimal tunjanganKeluarga) {
		this.tunjanganKeluarga = tunjanganKeluarga;
	}

	@Column(name = "tunjangan_pegawai", nullable = false, precision = 16, scale = 4)
	public BigDecimal getTunjanganPegawai() {
		return this.tunjanganPegawai;
	}

	public void setTunjanganPegawai(BigDecimal tunjanganPegawai) {
		this.tunjanganPegawai = tunjanganPegawai;
	}

	@Column(name = "tunjangan_transport", nullable = false, precision = 16, scale = 4)
	public BigDecimal getTunjanganTransport() {
		return this.tunjanganTransport;
	}

	public void setTunjanganTransport(BigDecimal tunjanganTransport) {
		this.tunjanganTransport = tunjanganTransport;
	}

	@Column(name = "gaji_kotor", nullable = false, precision = 16, scale = 4)
	public BigDecimal getGajiKotor() {
		return this.gajiKotor;
	}

	public void setGajiKotor(BigDecimal gajiKotor) {
		this.gajiKotor = gajiKotor;
	}

	@Column(name = "pph_perbulan", nullable = false, precision = 16, scale = 4)
	public BigDecimal getPphPerbulan() {
		return this.pphPerbulan;
	}

	public void setPphPerbulan(BigDecimal pphPerbulan) {
		this.pphPerbulan = pphPerbulan;
	}

	@Column(name = "bpjs", nullable = false, precision = 16, scale = 4)
	public BigDecimal getBpjs() {
		return this.bpjs;
	}

	public void setBpjs(BigDecimal bpjs) {
		this.bpjs = bpjs;
	}

	@Column(name = "gaji_bersih", nullable = false, precision = 16, scale = 4)
	public BigDecimal getGajiBersih() {
		return this.gajiBersih;
	}

	public void setGajiBersih(BigDecimal gajiBersih) {
		this.gajiBersih = gajiBersih;
	}

	@Column(name = "lama_lembur")
	public Integer getLamaLembur() {
		return this.lamaLembur;
	}

	public void setLamaLembur(Integer lamaLembur) {
		this.lamaLembur = lamaLembur;
	}

	@Column(name = "uang_lembur", nullable = false, precision = 16, scale = 4)
	public BigDecimal getUangLembur() {
		return this.uangLembur;
	}

	public void setUangLembur(BigDecimal uangLembur) {
		this.uangLembur = uangLembur;
	}

	@Column(name = "variable_bonus")
	public Integer getVariableBonus() {
		return this.variableBonus;
	}

	public void setVariableBonus(Integer variableBonus) {
		this.variableBonus = variableBonus;
	}

	@Column(name = "uang_bonus", nullable = false, precision = 16, scale = 4)
	public BigDecimal getUangBonus() {
		return this.uangBonus;
	}

	public void setUangBonus(BigDecimal uangBonus) {
		this.uangBonus = uangBonus;
	}

	@Column(name = "take_home_pay", nullable = false, precision = 16, scale = 4)
	public BigDecimal getTakeHomePay() {
		return this.takeHomePay;
	}

	public void setTakeHomePay(BigDecimal takeHomePay) {
		this.takeHomePay = takeHomePay;
	}

}
