//package com.employee.Employee.model;
//// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final
//
//import java.math.BigDecimal;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.SequenceGenerator;
//import javax.persistence.Table;
//
///**
// * TunjanganPegawai generated by hbm2java
// */
//@Entity
//@Table(name = "tunjangan_pegawai", schema = "public")
//public class TunjanganPegawai implements java.io.Serializable {
//
//	private int idTunjanganPegawai;
//	private Posisi posisi;
//	private Tingkatan tingkatan;
//	private BigDecimal besaranTujnaganPegawai;
//
//	public TunjanganPegawai() {
//	}
//
//	public TunjanganPegawai(int idTunjanganPegawai, BigDecimal besaranTujnaganPegawai) {
//		this.idTunjanganPegawai = idTunjanganPegawai;
//		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
//	}
//
//	public TunjanganPegawai(int idTunjanganPegawai, Posisi posisi, Tingkatan tingkatan,
//			BigDecimal besaranTujnaganPegawai) {
//		this.idTunjanganPegawai = idTunjanganPegawai;
//		this.posisi = posisi;
//		this.tingkatan = tingkatan;
//		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
//	}
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_tunjangan_pegawai_id_tunjangan_pegawai_seq")
//	@SequenceGenerator(name ="generator_tunjangan_pegawai_id_tunjangan_pegawai_seq", sequenceName="tunjangan_pegawai_id_tunjangan_pegawai_seq", schema = "public", allocationSize = 1)
//	@Column(name = "id_tunjangan_pegawai", unique = true, nullable = false)
//	public int getIdTunjanganPegawai() {
//		return this.idTunjanganPegawai;
//	}
//
//	public void setIdTunjanganPegawai(int idTunjanganPegawai) {
//		this.idTunjanganPegawai = idTunjanganPegawai;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_posisi")
//	public Posisi getPosisi() {
//		return this.posisi;
//	}
//
//	public void setPosisi(Posisi posisi) {
//		this.posisi = posisi;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "id_tingkatan")
//	public Tingkatan getTingkatan() {
//		return this.tingkatan;
//	}
//
//	public void setTingkatan(Tingkatan tingkatan) {
//		this.tingkatan = tingkatan;
//	}
//
//	@Column(name = "besaran_tujnagan_pegawai", nullable = false, precision = 16, scale = 4)
//	public BigDecimal getBesaranTujnaganPegawai() {
//		return this.besaranTujnaganPegawai;
//	}
//
//	public void setBesaranTujnaganPegawai(BigDecimal besaranTujnaganPegawai) {
//		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
//	}
//
//}
