package com.employee.Employee.model;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * UserId generated by hbm2java
 */


@Embeddable
public class UserId implements java.io.Serializable {

	private Integer idUser;
	private String username;

	public UserId() {
	}

	public UserId(Integer idUser, String username) {
		this.idUser = idUser;
		this.username = username;
	}
//	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_user_id_user_seq")
//	@SequenceGenerator(name="generator_user_id_user_seq", sequenceName="user_id_user_seq", schema = "public", allocationSize = 1)	
//	@Column(name = "id_user", nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}
//	@Id
//	@Column(name = "username", nullable = false, length = 128)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof UserId))
//			return false;
//		UserId castOther = (UserId) other;
//
//		return (this.getIdUser() == castOther.getIdUser())
//				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
//						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + this.getIdUser();
//		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
//		return result;
//	}

}
