package com.employee.Employee.model;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@IdClass(UserId.class)
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {
	
	private int idUser;
	private String username;
	private String password;
	private Short status;

	public User() {
	}

	public User(int idUser, String username, String password, Short status) {
		super();
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.status = status;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_user_id_user_seq")
	@SequenceGenerator(name="generator_user_id_user_seq", sequenceName="user_id_user_seq", schema = "public", allocationSize = 1)	
	@Column(name = "id_user", nullable = false)
	public int getidUser() {
		return idUser;
	}
	
	@Id
	@Column(name = "username", nullable = false, length = 128)
	public String getUsername() {
		return username;
	}

	public void setidUser(int idUser) {
		this.idUser = idUser;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

}
