package com.employee.model;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private int idUser;
	private String username;

	public UserId() {
	}

	public UserId(int idUser, String username) {
		this.idUser = idUser;
		this.username = username;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "username", nullable = false, length = 128)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
