package com.employee.Employee.dto;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

/**
 * ListKemampuan generated by hbm2java
 */
public class ListKemampuanDTO{

	private int idListKemampuan;
	private KemampuanDTO kemampuan;
	private KaryawanDTO karyawan;
	private Integer nilaiKemampuan;

	public ListKemampuanDTO() {
	}

	public ListKemampuanDTO(int idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	public ListKemampuanDTO(int idListKemampuan, KemampuanDTO kemampuan, KaryawanDTO karyawan, Integer nilaiKemampuan) {
		this.idListKemampuan = idListKemampuan;
		this.kemampuan = kemampuan;
		this.karyawan = karyawan;
		this.nilaiKemampuan = nilaiKemampuan;
	}

	public int getIdListKemampuan() {
		return this.idListKemampuan;
	}

	public void setIdListKemampuan(int idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	public KemampuanDTO getKemampuan() {
		return this.kemampuan;
	}

	public void setKemampuan(KemampuanDTO kemampuan) {
		this.kemampuan = kemampuan;
	}

	public KaryawanDTO getKaryawan() {
		return this.karyawan;
	}

	public void setKaryawan(KaryawanDTO karyawan) {
		this.karyawan = karyawan;
	}

	public Integer getNilaiKemampuan() {
		return this.nilaiKemampuan;
	}

	public void setNilaiKemampuan(Integer nilaiKemampuan) {
		this.nilaiKemampuan = nilaiKemampuan;
	}

}
