package com.employee.Employee.dto;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import com.employee.Employee.model.Karyawan;
import com.employee.Employee.model.Kemampuan;

/**
 * ListKemampuan generated by hbm2java
 */
public class ListKemampuanDTO{

	private int idListKemampuan;
	private Kemampuan kemampuan;
	private Karyawan karyawan;
	private Integer nilaiKemampuan;

	public ListKemampuanDTO() {
	}

	public ListKemampuanDTO(int idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	public ListKemampuanDTO(int idListKemampuan, Kemampuan kemampuan, Karyawan karyawan, Integer nilaiKemampuan) {
		this.idListKemampuan = idListKemampuan;
		this.kemampuan = kemampuan;
		this.karyawan = karyawan;
		this.nilaiKemampuan = nilaiKemampuan;
	}

	public int getIdListKemampuan() {
		return this.idListKemampuan;
	}

	public void setIdListKemampuan(int idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	public Kemampuan getKemampuan() {
		return this.kemampuan;
	}

	public void setKemampuan(Kemampuan kemampuan) {
		this.kemampuan = kemampuan;
	}

	public Karyawan getKaryawan() {
		return this.karyawan;
	}

	public void setKaryawan(Karyawan karyawan) {
		this.karyawan = karyawan;
	}

	public Integer getNilaiKemampuan() {
		return this.nilaiKemampuan;
	}

	public void setNilaiKemampuan(Integer nilaiKemampuan) {
		this.nilaiKemampuan = nilaiKemampuan;
	}

}
