package com.employee.Employee.dto;
// Generated Mar 30, 2020 8:42:38 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ParameterPajak generated by hbm2java
 */

public class ParameterPajakDTO{

	private int idParamPajak;
	private Date tbParameterPajak;
	private BigDecimal batasanPphK1;
	private BigDecimal batasanPphK2;
	private BigDecimal batasanPphK3;
	private BigDecimal batasanPphK4;
	private BigDecimal presentasePphK1;
	private BigDecimal presentasePphK2;
	private BigDecimal presentasePphK3;
	private BigDecimal presentasePphK4;
	private BigDecimal ptkpUtama;
	private BigDecimal ptkpTambahan;
	private Integer maxPtkpAnak;
	private BigDecimal biayaJabatan;
	private BigDecimal iuranPensiun;

	public ParameterPajakDTO() {
	}

	public ParameterPajakDTO(int idParamPajak, Date tbParameterPajak, BigDecimal batasanPphK1, BigDecimal batasanPphK2,
			BigDecimal batasanPphK3, BigDecimal batasanPphK4, BigDecimal presentasePphK1, BigDecimal presentasePphK2,
			BigDecimal presentasePphK3, BigDecimal presentasePphK4, BigDecimal ptkpUtama, BigDecimal ptkpTambahan,
			BigDecimal biayaJabatan, BigDecimal iuranPensiun) {
		this.idParamPajak = idParamPajak;
		this.tbParameterPajak = tbParameterPajak;
		this.batasanPphK1 = batasanPphK1;
		this.batasanPphK2 = batasanPphK2;
		this.batasanPphK3 = batasanPphK3;
		this.batasanPphK4 = batasanPphK4;
		this.presentasePphK1 = presentasePphK1;
		this.presentasePphK2 = presentasePphK2;
		this.presentasePphK3 = presentasePphK3;
		this.presentasePphK4 = presentasePphK4;
		this.ptkpUtama = ptkpUtama;
		this.ptkpTambahan = ptkpTambahan;
		this.biayaJabatan = biayaJabatan;
		this.iuranPensiun = iuranPensiun;
	}

	public ParameterPajakDTO(int idParamPajak, Date tbParameterPajak, BigDecimal batasanPphK1, BigDecimal batasanPphK2,
			BigDecimal batasanPphK3, BigDecimal batasanPphK4, BigDecimal presentasePphK1, BigDecimal presentasePphK2,
			BigDecimal presentasePphK3, BigDecimal presentasePphK4, BigDecimal ptkpUtama, BigDecimal ptkpTambahan,
			Integer maxPtkpAnak, BigDecimal biayaJabatan, BigDecimal iuranPensiun) {
		this.idParamPajak = idParamPajak;
		this.tbParameterPajak = tbParameterPajak;
		this.batasanPphK1 = batasanPphK1;
		this.batasanPphK2 = batasanPphK2;
		this.batasanPphK3 = batasanPphK3;
		this.batasanPphK4 = batasanPphK4;
		this.presentasePphK1 = presentasePphK1;
		this.presentasePphK2 = presentasePphK2;
		this.presentasePphK3 = presentasePphK3;
		this.presentasePphK4 = presentasePphK4;
		this.ptkpUtama = ptkpUtama;
		this.ptkpTambahan = ptkpTambahan;
		this.maxPtkpAnak = maxPtkpAnak;
		this.biayaJabatan = biayaJabatan;
		this.iuranPensiun = iuranPensiun;
	}

	public int getIdParamPajak() {
		return this.idParamPajak;
	}

	public void setIdParamPajak(int idParamPajak) {
		this.idParamPajak = idParamPajak;
	}


	public Date getTbParameterPajak() {
		return this.tbParameterPajak;
	}

	public void setTbParameterPajak(Date tbParameterPajak) {
		this.tbParameterPajak = tbParameterPajak;
	}

	public BigDecimal getBatasanPphK1() {
		return this.batasanPphK1;
	}

	public void setBatasanPphK1(BigDecimal batasanPphK1) {
		this.batasanPphK1 = batasanPphK1;
	}

	public BigDecimal getBatasanPphK2() {
		return this.batasanPphK2;
	}

	public void setBatasanPphK2(BigDecimal batasanPphK2) {
		this.batasanPphK2 = batasanPphK2;
	}


	public BigDecimal getBatasanPphK3() {
		return this.batasanPphK3;
	}

	public void setBatasanPphK3(BigDecimal batasanPphK3) {
		this.batasanPphK3 = batasanPphK3;
	}

	public BigDecimal getBatasanPphK4() {
		return this.batasanPphK4;
	}

	public void setBatasanPphK4(BigDecimal batasanPphK4) {
		this.batasanPphK4 = batasanPphK4;
	}


	public BigDecimal getPresentasePphK1() {
		return this.presentasePphK1;
	}

	public void setPresentasePphK1(BigDecimal presentasePphK1) {
		this.presentasePphK1 = presentasePphK1;
	}


	public BigDecimal getPresentasePphK2() {
		return this.presentasePphK2;
	}

	public void setPresentasePphK2(BigDecimal presentasePphK2) {
		this.presentasePphK2 = presentasePphK2;
	}

	public BigDecimal getPresentasePphK3() {
		return this.presentasePphK3;
	}

	public void setPresentasePphK3(BigDecimal presentasePphK3) {
		this.presentasePphK3 = presentasePphK3;
	}

	public BigDecimal getPresentasePphK4() {
		return this.presentasePphK4;
	}

	public void setPresentasePphK4(BigDecimal presentasePphK4) {
		this.presentasePphK4 = presentasePphK4;
	}

	public BigDecimal getPtkpUtama() {
		return this.ptkpUtama;
	}

	public void setPtkpUtama(BigDecimal ptkpUtama) {
		this.ptkpUtama = ptkpUtama;
	}

	public BigDecimal getPtkpTambahan() {
		return this.ptkpTambahan;
	}

	public void setPtkpTambahan(BigDecimal ptkpTambahan) {
		this.ptkpTambahan = ptkpTambahan;
	}

	public Integer getMaxPtkpAnak() {
		return this.maxPtkpAnak;
	}

	public void setMaxPtkpAnak(Integer maxPtkpAnak) {
		this.maxPtkpAnak = maxPtkpAnak;
	}

	public BigDecimal getBiayaJabatan() {
		return this.biayaJabatan;
	}

	public void setBiayaJabatan(BigDecimal biayaJabatan) {
		this.biayaJabatan = biayaJabatan;
	}

	public BigDecimal getIuranPensiun() {
		return this.iuranPensiun;
	}

	public void setIuranPensiun(BigDecimal iuranPensiun) {
		this.iuranPensiun = iuranPensiun;
	}

}
